---
title: <span style="color:#0085A1; font-size:5rem">Arizona SGP</span>
subtitle: "Technical Report"
author: |
  | <a href="https://dbetebenner.github.io/"><span style="font-size:2rem">Damian Betebenner</span></a> & <a href="https://adamvi.github.io/"><span style="font-size:2rem">Adam VanIwaarden</span></a>
  | <span style="color:#00274c">National Center for the Improvement of Educational Assessment</span>
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
    html_document:
        css: css/tufte.css
        highlight: pygments
        keep_md: no
        theme: cerulean
        toc: yes
        toc_float: yes
    bookdown::tufte_book2:
        includes:
            in_header: preamble.tex
#            before_body: before_body.tex
        latex_engine: xelatex
        citation_package: natbib
        number_sections: false
#        keep_tex: yes
bibliography: bibliography/refs.bib
#abstract: "This document provides an introduction to student growth percentiles (SGP)"
keywords: "SGP, student growth percentiles, student growth projections, R"
nocite: |
  @Betebenner:2009, @RSoftware, @SGP:2017, @ShangVanI:2015
---

```{r child='sections/Introduction.Rmd'}
```

```{r child='sections/Data.Rmd'}
```



# References
