---
title: <span style="color:#0085A1; font-size:5rem">Student Growth Percentiles</span>
subtitle: "Theory and Implementation in R"
author: "Damian W Betebenner & Adam VanIwaarden"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
    html_document:
        css: tufte-css-master/tufte.css
        highlight: pygments
        keep_md: no
        theme: cerulean
        toc: yes
        toc_float: yes
    bookdown::tufte_book2:
        includes:
            in_header: preamble.tex
            before_body: before_body.tex
        latex_engine: xelatex
        citation_package: natbib
#        keep_tex: yes
bibliography: bibliography/refs.bib
#abstract: "This document provides an introduction to student growth percentiles (SGP)"
keywords: "SGP, student growth percentiles, student growth projections, R"
nocite: |
  @Betebenner:2009, @RSoftware, @SGP:2017, @ShangVanI:2015
---



# [Preface](#preface)

The following provides a brief introduction to generalized additive models and some thoughts on getting started within the R environment.  It doesn't assume much more than a basic exposure to regression, and maybe a general idea of R though not necessarily any particular expertise. The presentation is of a very applied nature, and such that the topics build upon the familiar and generalize to the less so, with the hope that one can bring the concepts they are comfortable with to the new material. The audience in mind is a researcher with typical applied science training.

As this document is more conceptual, a basic familiarity with R is all that is needed to follow the code, though there is much to be gained from simple web browsing on R if one needs it. And while it wasn't the intention starting out, this document could be seen as a vignette for the <span class="pack">mgcv</span> package, which is highly recommended.


This document was created with [Rstudio](http://rstudio.org/) and rmarkdown. <span class="marginnote">Last modified `r Sys.Date()`. Original draft August, 2012.</span>

\cite{Betebenner:2009}

Color guide:

- <span class="emph">important term</span>
- [link]()
- <span class="pack">package</span>
- <span class="func">function</span>
- <span class="objclass">object or class</span>

R Info: **`r sessionInfo()$R.version$version.string` `r sessionInfo()$R.version$nickname`**



#<a name='conclusion'>Conclusion</a>

Generalized additive models are a conceptually straightforward tool that allows one to incorporate nonlinear predictor effects into their otherwise linear models. In addition, they allow one to keep within the linear and generalized linear modeling frameworks with which one is already familiar, while providing new avenues of model exploration and possibly improved results.  As was demonstrated, it is easy enough with just a modicum of familiarity to pull them off within the R environment, and as such, it is hoped that this document provides the means to do so.



# References
