---
title: <span style="color:#0085A1; font-size:5rem">Arizona SGP</span>
subtitle: "Technical Report"
author: |
  | <a href="https://dbetebenner.github.io/"><span style="font-size:2rem">Damian Betebenner</span></a> & <a href="https://adamvi.github.io/"><span style="font-size:2rem">Adam VanIwaarden</span></a>
  | <span style="color:#00274c">National Center for the Improvement of Educational Assessment</span>
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
    html_document:
        css: css/tufte.css
        highlight: pygments
        keep_md: no
        theme: cerulean
        toc: yes
        toc_float: yes
    bookdown::tufte_book2:
        includes:
            in_header: tex/preamble.tex
#            before_body: tex/before_body.tex
        latex_engine: xelatex
        citation_package: natbib
        number_sections: false
#        keep_tex: yes
bibliography: bibliography/refs.bib
#abstract: "This document provides an introduction to student growth percentiles (SGP)"
keywords: "SGP, student growth percentiles, student growth projections, R"
nocite: |
  @Betebenner:2009, @RSoftware, @SGP:2017, @ShangVanI:2015
---


# <a name='Data'>Data</a>

Data for the Arizona AzMERIT and AIMS assessments used in the SGP analyses were supplied by ADE to the NCIEA for analysis in the fall of 2016. In total, 4
years of data were provided by ADE: 2015-2016 (AzMERIT), 2014-2015 (AzMERIT), 2013-2014 (AIMS), and 2012-2013 (AIMS). Multiple years of data were provided
so that additional priors scores (beyond the minimum one required) could be used in the calculations. Subsequent years' analyses will augment this multi-year data set allowing
ADE to maintain a comprehensive longitudinal data set for their state assessment system.

Student Growth Percentiles have been produced for students that have a current score and at least one prior score in either the same subject or a related content area.  For the 2016 academic year SGPs were produced for grade-level English Language Arts (ELA), Mathematics, Science and Social Studies, as well as for EOC test subjects including 9<sup>th</sup> Grade Literature, American Literature, Coordinate Algebra, Analytic Geometry, Algebra I, Geometry, Physical Science, Biology, U.S. History and Economics.

## Longitudinal Data
Growth analyses on assessment data require data that are linked to individual students over time.  Student growth percentile analyses require, at a minimum two, and preferably three years of assessment data for analysis of student progress.  To this end it is necessary that a unique student identifier be available so that student data records across years can be merged with one another and subsequently examined.  Because some records in the assessment data set contain students with more than one test score in a content area in a given year, a process to create unique student records in each content area by year combination was required in order to carry out subsequent growth analyses.  Furthermore, student records may be invalidated for other reasons.  The following business rules were used to either invalidate particular student records or select the appropriate record for use in the analyses.

### General business rules

1.  Student records are invalidated if the student identifier is not exactly 10 digits long.
2.  Student records with missing ("NA") scores or scale scores outside of the possible range (usually 0) are invalidated.
3.  Student records with any administrative invalidation flag (for example, identifying test irregularities, students that did not attempt the test, or other issues) are invalidated.

Beginning in 2014 Georgia DOE has performed the majority of the selection and invalidation of student records, incorporating these and other business rules into the `SQL` code used to pull student records from their data warehouse.

<!-- HTML_Start -->
<!-- LaTeX_Start
\pagebreak
LaTeX_End -->


### EOG specific business rules

1.  If a student has multiple records (duplicate from the same subject, grade and administration period), their highest score was selected.
2.  If a student took more than one assessment in the same subject and school year but was identified as being in two different grades, the record with the highest grade level was selected.

Table shows the number of valid EOG student records available for analysis after applying the general and EOG specific business rules.^[This number does not represent the number of SGPs produced, however, because students are required to have at least one prior score available as well.]
