MATHEMATICS_2016.config <- list(
    MATHEMATICS_CBT.2016 = list(
                sgp.content.areas=c`('MATHEMATICS_CBT', 'MATHEMATICS_CBT'),
                sgp.panel.years=c('2015', '2016'),
                sgp.grade.sequences=list(c('3', '4'), c('4', '5'), c('5', '6'), c('6', '7'), c('7', '8'))),
    MATHEMATICS_PBT.2016 = list(
                sgp.content.areas=c`('MATHEMATICS_PBT', 'MATHEMATICS_PBT'),
                sgp.panel.years=c('2015', '2016'),
                sgp.grade.sequences=list(c('3', '4'), c('4', '5'), c('5', '6'), c('6', '7'), c('7', '8'))),
	ALGEBRA_I_CBT.2016 = list(
                sgp.content.areas=c('MATHEMATICS_CBT', 'ALGEBRA_I_CBT'),
                sgp.panel.years=c('2015', '2016'),
                sgp.grade.sequences=list(c('6', '7'), c('7', '8'), c('8', '9'))),
	ALGEBRA_I_PBT.2016 = list(
                sgp.content.areas=c('MATHEMATICS_PBT', 'ALGEBRA_I_PBT'),
                sgp.panel.years=c('2015', '2016'),
                sgp.grade.sequences=list(c('6', '7'), c('7', '8'), c('8', '9'))),
	GEOMETRY_CBT.2016 = list(
                sgp.content.areas=c('ALGEBRA_I_CBT', 'GEOMETRY_CBT'),
                sgp.panel.years=c('2015', '2016'),
                sgp.grade.sequences=list(c('7', '8'), c('8', '9'), c('9', '10'), c('10', '11'))),
	GEOMETRY_PBT.2016 = list(
                sgp.content.areas=c('ALGEBRA_I_PBT', 'GEOMETRY_PBT'),
                sgp.panel.years=c('2015', '2016'),
                sgp.grade.sequences=list(c('7', '8'), c('8', '9'), c('9', '10'), c('10', '11'))),
	ALGEBRA_II_CBT.2016 = list(
                sgp.content.areas=c('GEOMETRY_CBT', 'ALGEBRA_I_CBT'),
                sgp.panel.years=c('2015', '2016'),
                sgp.grade.sequences=list(c('8', '9'), c('9', '10'), c('10', '11'))),
	ALGEBRA_II_PBT.2016 = list(
                sgp.content.areas=c('GEOMETRY_PBT', 'ALGEBRA_I_PBT'),
                sgp.panel.years=c('2015', '2016'),
                sgp.grade.sequences=list(c('8', '9'), c('9', '10'), c('10', '11'))))
